apiVersion: v1
kind: Pod
metadata:
  name: pod-redistribute-2
spec:
  containers:
  - name: stress
    image: alpine
    command: ["sh", "-c", "apk add --no-cache stress-ng && stress-ng --cpu 1 --vm 1 --vm-bytes 300M --timeout 600s"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "200m"

