apiVersion: v1
kind: Pod
metadata:
  name: pod-redistribute-1
spec:
  containers:
  - name: stress
    image: alpine
    command: ["sh", "-c", "apk add --no-cache stress-ng && stress-ng --cpu 1 --vm 1 --vm-bytes 300M --timeout 600s"]
    resources:
      requests:
        memory: "300Mi"
        cpu: "300m"
      limits:
        memory: "500Mi"
        cpu: "500m"
