apiVersion: v1
kind: Pod
metadata:
  name: pod-no-affinity
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "prod"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
