apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.txt: "Начальнаывфывыфя конфигурацияяяяяя"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  secret.txt: YWRtaW4=   # SomeSecret
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-config-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command:
      - sh
      - -c
      - |
        while true; do
          echo "Конфигурация:";
          cat /etc/config/config.txt;
          echo "Секрет:";
          cat /etc/secret/secret.txt;
          sleep 10;
        done
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  - name: secret-volume
    secret:
      secretName: app-secret
