apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-svc
spec:
  type: NodePort
  selector:
    app: {{ include "mychart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
