apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  host: {{ .Values.database.host | b64enc }}
  port: {{ .Values.database.port | quote | b64enc }}
