apiVersion: v1
kind: Pod
metadata:
  name: busybox-memory-test
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do dd if=/dev/zero of=/dev/null bs=1M count=1024; done"]
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
