apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-configmap-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: app-account
  namespace: default
roleRef:
  kind: Role
  name: configmap-operator
  apiGroup: rbac.authorization.k8s.io
