name: Deploy Helm Chart

on:
  push:
    paths:
      - 'my-app/values.yaml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Configure Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy Application with Helm
        run: |
          helm upgrade --install my-app ./my-app -f ./my-app/values.yaml --namespace default
