name: Deploy Helm Chart

on:
  push:
    paths:
      - 'Module_7/Task6/mychart/values.yaml'  # Следим за изменениями в файле values.yaml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Configure Kubernetes
        run: |
          # Создаем конфиг Kubernetes из секрета
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl cluster-info  # Проверяем подключение к кластеру

      - name: Deploy Application with Helm
        run: |
          # Указываем правильный путь к Helm-чарту
          cd Module_7/Task6
          helm upgrade --install mychart-release ./mychart -f ./mychart/values.yaml --namespace default
