name: Deploy Helm Chart
on:
  push:
    paths:
      - 'Module_7/Task7/my-nginx/values.yaml'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up KUBECONFIG
        run: |
          echo "Используемый kubeconfig: %USERPROFILE%\.kube\config"
          set KUBECONFIG=%USERPROFILE%\.kube\config

      - name: Deploy with Helm
        run: |
          cd Module_7/Task7/my-nginx
          helm upgrade --install my-nginx . --values values.yaml --namespace my-namespace --create-namespace
