name: Deploy Helm Chart

on:
  push:
    paths:
      - 'Module_7/Task7/values.yaml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          mkdir %USERPROFILE%\.kube 2>nul || echo Folder exists
          copy /Y config %USERPROFILE%\.kube\config
        working-directory: .

      - name: Install Helm (if not installed)
        shell: powershell
        run: |
          if (!(Test-Path "$env:USERPROFILE\helm.exe")) {
            Write-Output "Helm not found. Installing..."
            Invoke-WebRequest -Uri "https://get.helm.sh/helm-v3.9.0-windows-amd64.zip" -OutFile "helm.zip"
            Expand-Archive -Path "helm.zip" -DestinationPath "."
            Move-Item -Path ".\windows-amd64\helm.exe" -Destination "$env:USERPROFILE\helm.exe"
          }
          else {
            Write-Output "Helm is already installed."
          }

      - name: Deploy/Upgrade Release via Helm
        shell: powershell
        run: |
          $helm = "$env:USERPROFILE\helm.exe"
          & $helm upgrade --install my-nginx helm-chart/ --values helm-chart/values.yaml
